version: "3"

services:
  picocms:
    restart: unless-stopped
    build: .
    image: picocms
    container_name: picocms
    command: "/run.sh"
    ports:
      - 80:80
    volumes:
      - ./config:/var/www/html/pico/config
      - ./content:/var/www/html/pico/content
      - ./plugins:/var/www/html/pico/plugins
      - ./themes:/var/www/html/pico/themes
      - ./logging:/var/log/pico
    networks:
      - picocms

networks:
  picocms:
    driver: bridge

# TODO: network needed here at all?
