version: "3"

services:
  picocms:
    restart: unless-stopped
    build: .
    image: picocms
    container_name: picocms
    command: "/run.sh"
    ports:
      - 80:80
    volumes:
      - ./config:/home/sites/picocms/config
      - ./content:/home/sites/picocms/content
      - ./plugins:/home/sites/picocms/plugins
      - ./themes:/home/sites/picocms/themes
    networks:
      - picocms

networks:
  picocms:
    driver: bridge
